#pragma once
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mizar_jni_MizaRaster */

#ifndef _Included_com_mizar_jni_MizaRaster
#define _Included_com_mizar_jni_MizaRaster
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mizar_jni_MizaRaster
 * Method:    getDouble
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mizar_jni_MizaRaster_getDouble (JNIEnv *, jclass, jint);
JNIEXPORT jint JNICALL Java_com_mizar_jni_MizaRaster_openGDALDatasource (JNIEnv *, jclass, jstring userName, jstring password, jstring tnsname, jstring tableNames);
JNIEXPORT jint JNICALL Java_com_mizar_jni_MizaRaster_closeGDALDatasource (JNIEnv *, jclass, jint);
#ifdef __cplusplus
}
#endif
#endif
