create unique index DLM_0_ARTIFICIAL_PK on DLM_0_ARTIFICIAL(ID);
create unique index DLM_0_BUILDING_PK on DLM_0_BUILDING(ID);
create unique index DLM_0_DIVISION_PK on DLM_0_DIVISION(ID);
create unique index DLM_0_EXPOSED_PK on DLM_0_EXPOSED(ID);
create unique index DLM_0_LOCALE_PK on DLM_0_LOCALE(ID);
create unique index DLM_0_RAIL_SEGMENT_PK on DLM_0_RAIL_SEGMENT(ID);
create unique index DLM_0_SITE_PK on DLM_0_SITE(ID);
create unique index DLM_0_STRUCTURE_PK on DLM_0_STRUCTURE(ID);
create unique index DLM_0_VEGETATION_PK on DLM_0_VEGETATION(ID);
create unique index DLM_0_WATER_PK on DLM_0_WATER(ID);
create unique index DLM_0_WATER_SINGLE_PK on DLM_0_WATER_SINGLE(ID);
create unique index DLM_0_WAY_PK on DLM_0_WAY(ID);
create index DLM12_WAY_IDX on DLM12_WAY(POLY_GEOM_VALUE) indextype is mdsys.spatial_index;
create index DLM_0_ARTIFICIAL_PSDX on DLM_0_ARTIFICIAL(POLY_GEOM_VALUE) indextype is mdsys.spatial_index;
create index DLM_0_BUILDING_PSDX on DLM_0_BUILDING(POLY_GEOM_VALUE) indextype is mdsys.spatial_index;
create index DLM_0_BUILDING_TSDX on DLM_0_BUILDING(PNT_GEOM_VALUE) indextype is mdsys.spatial_index;
create index DLM_0_DIVISION_LSDX on DLM_0_DIVISION(LINE_GEOM_VALUE) indextype is mdsys.spatial_index;
create index DLM_0_EXPOSED_PSDX on DLM_0_EXPOSED(POLY_GEOM_VALUE) indextype is mdsys.spatial_index;
create index DLM_0_LOCALE_PSDX on DLM_0_LOCALE(POLY_GEOM_VALUE) indextype is mdsys.spatial_index;
create index DLM_0_LOCALE_TSDX on DLM_0_LOCALE(PNT_GEOM_VALUE) indextype is mdsys.spatial_index;
create index DLM_0_RAIL_SEGMENT_LSDX on DLM_0_RAIL_SEGMENT(LINE_GEOM_VALUE) indextype is mdsys.spatial_index;
create index DLM_0_SITE_PSDX on DLM_0_SITE(POLY_GEOM_VALUE) indextype is mdsys.spatial_index;
create index DLM_0_STRUCTURE_TSDX on DLM_0_STRUCTURE(GEOM_VALUE) indextype is mdsys.spatial_index;
create index DLM_0_VEGETATION_PSDX on DLM_0_VEGETATION(POLY_GEOM_VALUE) indextype is mdsys.spatial_index;
create index DLM_0_WATER_LSDX on DLM_0_WATER(LINE_GEOM_VALUE) indextype is mdsys.spatial_index;
create index DLM_0_WATER_PSDX on DLM_0_WATER(POLY_GEOM_VALUE) indextype is mdsys.spatial_index;
create index DLM_0_WATER_SINGLE_LSDX on DLM_0_WATER_SINGLE(LINE_GEOM_VALUE) indextype is mdsys.spatial_index;
create index DLM_0_WAY_LSDX on DLM_0_WAY(LINE_GEOM_VALUE) indextype is mdsys.spatial_index;
create index DLM_0_WAY_PSDX on DLM_0_WAY(POLY_GEOM_VALUE) indextype is mdsys.spatial_index;
